import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/general/header/header';
import Footer from '@/components/general/footer/footer';
import { Toaster } from '@/components/ui/sonner';
import { RqProvider } from '@/utils/rq/react-query-provider';
import { getQueryClient } from '@/utils/rq/react-query-client';
import { dehydrate } from '@tanstack/react-query';
import { ReactQueryHydrate } from '@/utils/rq/react-query-hydrate';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = getQueryClient();
  const dehydrateState = dehydrate(queryClient);
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col overflow-y-auto bg-zinc-900 text-zinc-50`}>
        <RqProvider>
          <ReactQueryHydrate state={dehydrateState}>
            <Header />
            {children}
            <Footer />
            <Toaster richColors />
          </ReactQueryHydrate>
        </RqProvider>
      </body>
    </html>
  );
}
